### ISSUE TITLE
All blog posts 404

### ISSUE THREAD

**Issue by FilledStacks** [gridsome/gridsome-starter-blog#38]
Hi there,

I downloaded the blog code. Using the instructions below. 

1. gridsome create my-gridsome-site https://github.com/gridsome/gridsome-starter-blog.git
2. cd my-gridsome-site to open folder
3. **yarn upgrade --latest**
4. gridsome develop to start local dev server at http://localhost:8080

The upgraded to the latest. 

**Expectation**
The blog builds and runs normally. When clicking on a blog post it should show the blog details from the markdown

**Actual Result**
404 page not found for all blog posts.

Here is my package json. I'm on gridsome 0.7.2 and the latest for all the plugins.

```javascript
{
  "name": "my-gridsome-site",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/plugin-google-analytics": "^0.1.0",
    "@gridsome/remark-prismjs": "^0.2.0",
    "@gridsome/source-filesystem": "^0.6.0",
    "@gridsome/transformer-remark": "^0.3.3",
    "gridsome": "^0.7.2"
  },
  "devDependencies": {
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.0"
  }
}
```

**Comment by suits-at** [comment]
I think the problem here is that this starter is not up-to-date and there are some changes in the most recent versions of gridsome. I have it up and running with version ` "gridsome": "^0.6.9"`. I might try to update to 0.7.2 soon if I find time, and let you know if it works for me.

**Comment by FilledStacks** [comment]
@suits-at that would be great. Thank you very much.

The reason I upgraded to 0.7.2 is because I was still on 0.5.2 and gridsome/vue-remark wasn't playing nice in there. I might go down a few versions as well and see if I can get vue-remark plugin working and the rest of my website not to bomb out. I can't lose my blogs url now since I'm getting lots of traffic through google search to specific urls.

**Comment by suits-at** [comment]
I dont'use vue-remark but you can have a look at my [package.json](https://github.com/suits-at/netlifycms-gridsome/blob/master/package.json) maybe this helps temporarily.

**Comment by FilledStacks** [comment]
Thanks. I'll be able to check it out tomorrow. I'll try the lower versions and see if I can get it working with vue-remark

**Comment by FilledStacks** [comment]
@suits-at Quick update. 

Version 0.6.9 works in terms of the paths being generated properly. Just had to adjust some of my code block css to remove the background and borders around the lines of code. 

Vue-Remark is still not working. I'll open a different bug for that on the main gridsome-repo. Thanks for your help.
