### ISSUE TITLE
How to keep aspect ratio of Responsive images?

### ISSUE THREAD

**Issue by LorenAmelang** [gridsome/gridsome-starter-blog#48]
For way too much background, see:
https://github.com/calebanthony/gridsome-bulma/issues/9

Briefly,  when the image class:

`<figure class="image is-2by1"><img alt="Cover image" src="data:image/svg+xml,%3csvg  fill='none' viewBox='0 0 770 385' ... `

is put in this container, it works as expected:

`<div class="card"><a href="/new/consumed-by-the-light" class="card-image">`

But put in this container it gets huge margins that don't appear to be scaled in Responsive displays, and loses its aspect ratio - it shrinks more horizontally: 

`<div class="post content section container">`

I've found if I hack the generated index.html for the distorted page to add: 

`src="data:image/svg+xml,%3csvg fill='none' viewBox='0 0 770 385' preserveAspectRatio="xMidYMid meet"`

The aspect ratio is preserved - but I get only the blur image, and it is even tinier. And I don't know where to put it so it builds into the project automatically.  

I saw another suggestion to add, in post.vue:

`    cover_image(width: 770, immediate: true, fit: inside, blur: 1)`

But that won't build, it won't accept "immediate" even though it is in the same list with width, fit, and blur. 

Pretty much everything else about this project has worked well, but this one is way beyond my knowledge! Is there any way to force the "Post" images to keep their aspect ratio on "Responsive" screens like the "Index" images do?

**Comment by calebanthony** [comment]
This is pretty specifically a Bulma problem. Feel free to close this here and I'll resolve it in [calebanthony/gridsome-bulma#9](https://github.com/calebanthony/gridsome-bulma/issues/9)

**Comment by LorenAmelang** [comment]
Thanks to Caleb's suggestion, I've moved my image out of the `<div class="post content section container">` and put it into its own simpler div:

```
    <div class="has-text-centered">
      <g-image
        alt="Cover image"
        :src="$page.post.cover_image"
      />
    </div>

```
And my images are now properly aspected!
