### ISSUE TITLE
GraphQL Query Error caused by coverImage

### ISSUE THREAD

**Issue by lauragift21** [gridsome/gridsome-starter-blog#8]
I keep coming across this error whenever I delete a post with cover_image in the frontmatter. The error thrown is 

```
Error: Unknown argument "width" on field "coverImage" of type "Post".
```

**Comment by hjvedvik** [comment]
Does this happen while the development server is running or when you start up again after deleting a post?

**Comment by lauragift21** [comment]
It happens when I delete the post and start up the server again.

**Comment by hjvedvik** [comment]
I see. Gridsome creates the GraphQL schema based on fields it finds at startup, so that's probably why the `coverImage` isn't an image field sometimes. We are working on a solution to make Gridsome remember the schema instead of just looking up fields on nodes every time you start the development server, but it's not ready yet :)

**Comment by lauragift21** [comment]
Alright, that makes sense. Looking forward to that fix.

**Comment by SamUndefined** [comment]
@lauragift21 Have you by chance found a decent workaround in the meantime? 

Locally, I've been deleting those arguments, starting the server, and then re-adding them after reboot. On (Netlify) deploy, I just run deploy until it works 😬

**Comment by lauragift21** [comment]
No I haven't yet. I'm hoping the fix get merged in soon enough.

**Comment by kendallroth** [comment]
I've had this happen whenever I change the image path in frontmatter as follows:

```
# Builds and displays
cover_image: /images/test.jpg

# Builds but does not display image (doesn't exist?)
cover_image: ./images/test.jpg

# Doesn't build and displays this error (path saved by Netlify CMS)
cover_image: images/test.jpg
```

**Comment by Xstoudi** [comment]
Is there an update about this issue ? How can I re-generate the GraphQL schem ?

**Comment by miralize** [comment]
Is there a workaround for this, @hjvedvik?

**Comment by eleijonmarck** [comment]
@Xstoudi @miralize Have you tried?
```
rm -rf node_modules
rm -rf .cache
```

**Comment by dizid** [comment]
Here is a [plugin](https://germano.dev/fix-netlify-cms-paths-on-gridsome/) that might fix this error

**Comment by RehanSaeed** [comment]
I'm getting this error on GitHub actions when doing a build, not develop. Is there any workaround?

**Comment by RehanSaeed** [comment]
Did you find a resolution? I raised https://github.com/gridsome/gridsome/issues/1031.
