### ISSUE TITLE
Css classes are duplicated

### ISSUE THREAD

**Issue by awulkan** [gridsome/gridsome-starter-blog#9]
Here's an example from the root index page.

![image](https://i.imgur.com/QCpZimb.png)

It only happens on built sites, not in dev mode. Which means the blog is serving a bunch of extra css that is useless.

Edit: It appears like the Casper theme and Gridsome site are also experiencing duplicate css, leading me to assume it's a more fundamental problem in Gridsome.

**Comment by hjvedvik** [comment]
I think it's a problem with code-splitting and CSS. The next version of Gridsome will only output one CSS file to fix this (gridsome/gridsome#230).

**Comment by awulkan** [comment]
Let, let's wait and see then. I remember having the same problem in Vue once when I imported scss files with classes in it into the wrong config file.

Any ETA on Gridsome 0.6?

**Comment by hjvedvik** [comment]
The CSS fix will be published before `0.6` :) I'm not sure when `0.6` will be published yet. We are still collecting issues that we want to include [here](https://github.com/gridsome/gridsome/milestone/1).

**Comment by awulkan** [comment]
Btw, here's the issue I ran into.

https://github.com/vuejs/vue-loader/issues/110

https://vueschool.io/articles/vuejs-tutorials/globally-load-sass-into-your-vue-js-applications/



Extract from the last article:

"Caveats

You have to make sure that the files that you import in the data configuration contain only SASS code that doesn’t get rendered, such as variables, mixins and functions. Otherwise, that code will end up repeated for each component in the final post-processed css file.

That’s just the way it works: vue-loader will prepend all those files you’ve defined in each component CSS’s."

**Comment by awulkan** [comment]
This appears to be fixed in the latest release. Should we close it?

**Comment by hjvedvik** [comment]
Yes, you can probably close this. There shouldn't be any duplicate CSS problems in `0.5.5` :)

**Comment by awulkan** [comment]
Closed, great work btw!
